### ISSUE TITLE
Using pypotrace on osx?

### ISSUE THREAD

**Issue by fabiantheblind** [flupke/pypotrace#3] opened 2013-03-08 17:02 UTC
Hi there,
I would love to use your lib on Mac OSX 10.8? Is it possible to do that?

**Comment by ArchieT** [comment] 2015-04-04 20:13
Yeah, I have the problem with potracelib.h on OS X as well as on Linux, and any suggestions would be appreciated. BTW, the not-automatically-handled dependency Cython.Distutils is kinda' annoying as well.

**Comment by ArchieT** [comment] 2015-04-05 10:00
I've walked through all the steps of your unsuccessful attempt, and it ain't started working yet.

And maybe it's kinda' off-topic, but I have a problem which may be caused by pypotrace: Archiet/armpen#1 (on Linux)

**Comment by gerardonunez** [comment] 2015-09-25 17:54
If someone is interested in installing pypotrace on MacOS, try following the steps below:

1. install potrace and antigraingeometry (agg) from maports:
        sudo port install potrace
        sudo port install antigraingeometry

      -> it will install libs on /opt/local/lib and the respective include files on /opt/local/include

2. Make a symlink to the agg dynamic library:
      cd /opt/local/lib
      ln -s libagg.dylib libagg_pic.dylib

3. Install cython:
      pip install cython

4. Determine the location of the site-packages directory. You can get with:

      export PYTHONSITEPKG=$(python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())")
      echo $PYTHONSITEPKG

      If you are working from a virtual env with default configuration it should probably look as:
          /Users/yourlogin/.virtualenvs/yourvirtenv/lib/python2.7/site-packages

5. Check you do have numpy installed for this version of python. For example:
    ls $PYTHONSITEPKG/numpy

6. Install pypotrace telling the compiler where to find the include files (-I) and the libraries (-L):

    pip install \
        --global-option=build_ext \
        --global-option="-I/opt/local/include:$PYTHONSITEPKG/numpy/core/include" \
        --global-option='-L/opt/local/lib'  \
        pypotrace


(Worked with:  MacOS 10.9.4 and  Python 2.7.5)

**Comment by flupke** [comment] 2015-09-29 22:13
I now have access to a mac and updated the setup.py. It now relies on pkg-config for libagg and build should be more reliable accross platforms. numpy include directories are also now retrieved with `numpy.get_include()`.

The README is updated and building should be more simple now. I tried the instructions on OSX 10.10 and Ubuntu 14.04, but I would appreciate if you could try on your systems.

I also regenerated the cython extensions and fixed a segfault when passing `None` to `Bitmap` constructor.

**Comment by flupke** [comment] 2015-10-01 19:41
No news is good news, I'll close the issue. Don't hesitate to reopen it if you encounter any problem.

**Closed by flupke** 2015-10-01 19:41 UTC

**Comment by justmichaelwang** [comment] 2018-04-11 05:51
Hi there, 
I am on OS 10.11.2,
when i did the last step which is $pip install .

It gives me the output below:
Processing /Users/mwang/Desktop/HappyHackers/re/PyOpenGL_season_02/pypotrace
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/73/661v1s_d41j4bv5twvpsykgw0000gp/T/pip-hmzb96jc-build/setup.py", line 70, in <module>
        cython=CYTHONIZE),
      File "/private/var/folders/73/661v1s_d41j4bv5twvpsykgw0000gp/T/pip-hmzb96jc-build/setup.py", line 51, in create_ext_obj
        pkg_config_flags = get_flags(flags, flag)
      File "/private/var/folders/73/661v1s_d41j4bv5twvpsykgw0000gp/T/pip-hmzb96jc-build/setup.py", line 24, in get_flags
        return [flag[2:] for flag in flags if flag.startswith(prefix)]
      File "/private/var/folders/73/661v1s_d41j4bv5twvpsykgw0000gp/T/pip-hmzb96jc-build/setup.py", line 24, in <listcomp>
        return [flag[2:] for flag in flags if flag.startswith(prefix)]
    TypeError: startswith first arg must be bytes or a tuple of bytes, not str

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/73/661v1s_d41j4bv5twvpsykgw0000gp/T/pip-hmzb96jc-build/

Would anybody be so kind to help me?

**Comment by justmichaelwang** [comment] 2018-04-11 05:54
BTW, i am using Python 3.5.4 :: Anaconda custom (x86_64)

**Comment by yig** [comment] 2019-01-10 19:22
This is fixed on github, but apparently not the version on PyPI. Try:

`pip3 install -e git+https://github.com/flupke/pypotrace#egg=pypotrace`

**Comment by yig** [comment] 2019-01-11 00:15
UPDATE: This is now fixed on PyPI. `pip3 install pypotrace` should work.

**Comment by whistler** [comment] 2020-07-28 03:57
`pip3 install pypotrace` does not work for me but `pip3 install -e git+https://github.com/flupke/pypotrace#egg=pypotrace` does.

**Comment by shreevatsa** [comment] 2020-11-09 22:57
It's already mentioned at https://github.com/flupke/pypotrace#osx ([link](https://github.com/flupke/pypotrace/blob/614a1a7/README.rst#osx)), but don't forget to run:

```
brew install libagg pkg-config potrace
```

before `pip3 install pypotrace`.

**Comment by vwrobel** [comment] 2021-01-30 13:02
Hi all,

I am on OS X Big Sur 11.1.

I have run brew install libagg pkg-config potrace successfully.

I use a conda environment with Python 3.7.4, Cython==0.29.13 and numpy 1.17.4.

Wheter I do `pip3 install pypotrace` or `pip3 install -e git+https://github.com/flupke/pypotrace#egg=pypotrace` or `git clone... pip install .`, I get this error trace:

```
Installing collected packages: pypotrace
  Running setup.py develop for pypotrace
    ERROR: Command errored out with exit status 1:
     command: /Users/vwrobel/opt/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/vwrobel/Workshop/src/pypotrace/setup.py'"'"'; __file__='"'"'/Users/vwrobel/Workshop/src/pypotrace/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /Users/vwrobel/Workshop/src/pypotrace/
    Complete output (18 lines):
    running develop
    running egg_info
    writing pypotrace.egg-info/PKG-INFO
    writing dependency_links to pypotrace.egg-info/dependency_links.txt
    writing requirements to pypotrace.egg-info/requires.txt
    writing top-level names to pypotrace.egg-info/top_level.txt
    reading manifest file 'pypotrace.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    writing manifest file 'pypotrace.egg-info/SOURCES.txt'
    running build_ext
    building 'potrace._potrace' extension
    x86_64-apple-darwin13.4.0-clang -fno-strict-aliasing -Wsign-compare -Wunreachable-code -DNDEBUG -fwrapv -O3 -Wall -Wstrict-prototypes -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O3 -pipe -fdebug-prefix-map=${SRC_DIR}=/usr/local/src/conda/${PKG_NAME}-${PKG_VERSION} -fdebug-prefix-map=/Users/vwrobel/opt/anaconda3=/usr/local/src/conda-prefix -flto -Wl,-export_dynamic -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O3 -march=core2 -mtune=haswell -mssse3 -ftree-vectorize -fPIC -fPIE -fstack-protector-strong -O2 -pipe -isystem /Users/vwrobel/opt/anaconda3/envs/workshop/include -D_FORTIFY_SOURCE=2 -mmacosx-version-min=10.9 -isystem /Users/vwrobel/opt/anaconda3/envs/workshop/include -I/Users/vwrobel/.local/lib/python3.7/site-packages/numpy/core/include -I/Users/vwrobel/opt/anaconda3/include/python3.7m -c potrace/_potrace.c -o build/temp.macosx-10.9-x86_64-3.7/potrace/_potrace.o
    clang-10: warning: -Wl,-export_dynamic: 'linker' input unused [-Wunused-command-line-argument]
    potrace/_potrace.c:618:10: fatal error: 'potracelib.h' file not found
    #include "potracelib.h"
             ^~~~~~~~~~~~~~
    1 error generated.
    error: command 'x86_64-apple-darwin13.4.0-clang' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/vwrobel/opt/anaconda3/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/Users/vwrobel/Workshop/src/pypotrace/setup.py'"'"'; __file__='"'"'/Users/vwrobel/Workshop/src/pypotrace/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.

```

potracelib.h is symlinked to /usr/local/include by homebrew.

I would appreciate very much any help!

**Comment by vwrobel** [comment] 2021-02-01 15:15
In case anyone runs into the above problem: I could not install pypotrace in a conda environment but it is ok on a virtualenv (I had to reinstall homebrew though in my particular case).
